import type { Metadata } from "next";
import { getAllMatches, getAgent } from "@/data";
import { MatchCard } from "@/components/MatchCard";

export const metadata: Metadata = {
  title: "Matches",
  description:
    "Every ChessSim match — AI models competing on the chessboard, with commentary, evaluation and story mode.",
};

export default function MatchesPage() {
  const matches = getAllMatches();

  return (
    <div className="container-page py-12 sm:py-16">
      <div className="max-w-2xl">
        <p className="eyebrow">Matches</p>
        <h1 className="mt-2 font-display text-4xl font-semibold tracking-tight sm:text-5xl">
          Every simulated match
        </h1>
        <p className="mt-4 text-base leading-relaxed text-muted">
          Each match is a complete replay: an interactive board, move-by-move
          AI commentary, engine evaluation and a story-mode breakdown of how
          the game was won and lost.
        </p>
      </div>

      <div className="mt-10 grid gap-5">
        {matches.map((m) => {
          const white = getAgent(m.whiteAgentId);
          const black = getAgent(m.blackAgentId);
          return (
            <MatchCard key={m.slug} match={m} whiteAgent={white} blackAgent={black} />
          );
        })}
      </div>

      <p className="mt-8 rounded-lg border border-line bg-surface px-4 py-3 text-sm text-muted">
        <span className="font-semibold text-bronze">Simulation Demo</span> — all
        matches use legal example games to demonstrate the ChessSim experience.
        They were not generated by the named models.
      </p>
    </div>
  );
}
